#command line for music playback and stop
- platform: command_line
  switches:
    music:
      command_on: "/home/music/play"
      command_off: "/home/music/stop"
    volume:
      command_on: "/home/music/volUp"
      command_off: "/home/music/volDown"
- platform: mqtt
  name: "Nappali Lámpa"
  command_topic: "cmnd/nappali_lampa/power"
  state_topic: "stat/nappali_lampa/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
